#Start Up / Settings / General
StartUp: '&4ArmorStand Plugin started.'
ShowCloseOpenMenuMessage: true
OpenCreateMessage:  '&4You opened the ArmorStand Create Menu.'
ClosingMainMenu:  '&3You closed the Main Menu.'
ClosingCreateMenu:  '&4You closed the ArmorStand Create Menu.'
OptionConfirmed:  '&2You saved your Option.'
OptionCanceld:  '&4You canceled your Option.'
ArmorStandCreated:  '&2You created your custom ArmorStand.'
NotAPlayer: '&4You are not a player.'
#Armor
HelmetAdded:  '&2Added your Helmet.'
HelmetRemoved:  '&4Removed your Helmet.'
ChestplateAdded:  '&2Added your Chestplate.'
ChestplateRemoved:  '&4Removed your Chestplate.'
LeggingsAdded:  '&2Added your Leggings.'
LeggingsRemoved:  '&4Removed your Leggings.'
BootsAdded: '&2Added your Boots.'
BootsRemoved:  '&4Removed your Boots.'
ElytraRemoved:  '&4Removed your Elytra.'
ElytraAdded:  '&2Added your Elytra.'
#Menu Names
MainMenuName: '&4Main Menu'
CreateMenuName: '&eCreate a ArmorStand'
ConfirmMenuName:  '&2Confirm'
ArmorMenuName:  '&1Armor Menu'
#Icon Names
ElytraIconName: '&5Gives your ArmorStand a Elytra or not.'
DiamondHelmetIconName:  '&3Gives your ArmorStand a Helmet or not.'
DiamondChestplateIconName:  '&3Gives your ArmorStand a Chestplate or not.'
DiamondLeggingsIconName:  '&3Gives your ArmorStand a Leggings or not.'
DiamondBootsIconName:  '&3Gives your ArmorStand Boots or not.'
CreateIconName: '&3Create'
CloseIconName:  '&cClose'
GlowIconName: '&eGlow'
ArmsIconName: '&cArms'
ArmorIconName:  '&aArmor'
ArmorplateIconName: '&bArmorStandBottom'
ImmortalIconName: '&eMake the ArmorStand immortal.'
CompleteIconName: '&2Complete'
CancelIconName: '&4Cancel'
YesIconName:  '&2Yes'
NoIconName: '&4No'
DoneIconName: '&2Done'
#Lore Names
CreateLore: 'Creates a Custom ArmorStand.'
GlowLore: 'Makes you ArmorStand glow.'
ArmsLore: 'Makes that your ArmorStand has Arms.'
ArmorLore:  'Makes your ArmorStand has Armor.'
ArmorplateLore:  'Lets your ArmorStand has a Bottom.'
GetArms:  '&1Give Arms?'
IsGlowing:  '&2Let it glow?'
ImmortalLore: 'Makes your ArmorStand immortal.'
Immortal: '&eWant to make your ArmorStand Immortal?'
GiveArmor:  '&cGive the ArmorStand Armor?'
GiveBasePlate:  '&3Give the ArmorStand a bottom?'